  0         LOADL        0
  1         CALL         newarr  
  2         CALL         L10
  3         HALT   (0)   
  4  L10:   LOADL        5
  5         CALL         newarr  
  6         LOAD         3[LB]
  7         CALL         arraylen
  8         CALL         putintnl
  9         LOADL        -1
 10         LOADL        2
 11         CALL         newobj  
 12         LOAD         4[LB]
 13         LOADL        1
 14         LOADL        -1
 15         LOADL        1
 16         CALL         newobj  
 17         CALL         fieldupd
 18         LOAD         4[LB]
 19         LOADL        0
 20         LOADL        10
 21         CALL         newarr  
 22         CALL         fieldupd
 23         LOAD         4[LB]
 24         LOADL        1
 25         CALL         fieldref
 26         LOADL        0
 27         LOADL        20
 28         CALL         newarr  
 29         CALL         fieldupd
 30         LOAD         4[LB]
 31         LOADL        0
 32         CALL         fieldref
 33         CALL         arraylen
 34         CALL         putintnl
 35         LOAD         4[LB]
 36         LOADL        1
 37         CALL         fieldref
 38         LOADL        0
 39         CALL         fieldref
 40         CALL         arraylen
 41         CALL         putintnl
 42         RETURN (0)   1
